//
//  FakeData.swift
//  Mussiiker
//
//  Created by Jhen Mu on 2023/1/28.
//

import Foundation


class FakeData {
    
    let TeacherData: [Teacher] = [
        Teacher(basicData: BasicData(name: "Tina",
                                     age: 20,
                                     gender: .female,
                                     birthDay: Date(),
                                     professional: ["Guitar","Drums"],
                                     photo: ["teacher-01"],
                                     phone: "0912122212",
                                     email: "xxxxx@gmail.com"),
                
                teachingHistory: .init(isHadTeachingExperience: true, teachingAge: 2),
                
                teachingStyle: .init(hopeTeachingSpendingPerHour: 1,
                                     hopeTeachingArea: [.middle,.north],
                                     hopeTeachingLocation: ["木匠工作室"],
                                     acceptRemoteTeaching: true,
                                     acceptFreeTeaching: true,
                                     teachingType: [.oneByOne,.teamLearning],
                                     isUnderGraduate: true,
                                     hopeLearnGender: [.female,.male],
                                     teachingReason: .profession)),
        Teacher(basicData: .init(name: "Guan",
                                 age: 22,
                                 gender: .female,
                                 birthDay: Date(),
                                 professional: ["Piano"],
                                 photo: ["teacher-02"],
                                 phone: "0987887788",
                                 email: "oooo@gmail.com"),
                teachingHistory: .init(isHadTeachingExperience: true, teachingAge: 1),
                teachingStyle: .init(hopeTeachingSpendingPerHour: 1,
                                     hopeTeachingArea: [.east,.south],
                                     hopeTeachingLocation: ["xx工作室"],
                                     acceptRemoteTeaching: false,
                                     acceptFreeTeaching: false,
                                     teachingType: [.teamLearning,.learnBySelf],
                                     isUnderGraduate: true,
                                     hopeLearnGender: [.male,.female],
                                     teachingReason: .partTime)),
        Teacher(basicData: .init(name: "Ben",
                                 age: 25,
                                 gender: .male,
                                 birthDay: Date(),
                                 professional: ["Ukulele"],
                                 photo: ["teacher-03"],
                                 phone: "09338366636",
                                 email: "xxxxx@gmail.com"),
                teachingHistory: .init(isHadTeachingExperience: true,
                                       teachingAge: 3),
                teachingStyle: .init(hopeTeachingSpendingPerHour: 0.5,
                                     hopeTeachingArea: [.rural,.east],
                                     hopeTeachingLocation: ["花蓮工作室"],
                                     acceptRemoteTeaching: true,
                                     acceptFreeTeaching: false,
                                     teachingType: [.learnBySelf,.teamLearning],
                                     isUnderGraduate: true,
                                     hopeLearnGender: [.male,.female],
                                     teachingReason: .profession)),
        Teacher(basicData: .init(name: "Festa",
                                 age: 30,
                                 gender: .male,
                                 birthDay: Date(),
                                 professional: ["Drums"],
                                 photo: ["teacher-04"],
                                 phone: "0937666363",
                                 email: "xxxxx@gmail.com"),
                teachingHistory: .init(isHadTeachingExperience: true,
                                       teachingAge: 2),
                teachingStyle: .init(hopeTeachingSpendingPerHour: 1,
                                     hopeTeachingArea: [.north],
                                     hopeTeachingLocation: ["北漂音樂工作室"],
                                     acceptRemoteTeaching: true,
                                     acceptFreeTeaching: false,
                                     teachingType: [.oneByOne],
                                     isUnderGraduate: true,
                                     hopeLearnGender: [.male,.female],
                                     teachingReason: .profession)),
        Teacher(basicData: .init(name: "Jake",
                                 age: 26,
                                 gender: .male,
                                 birthDay: Date(),
                                 professional: ["Cello"],
                                 photo: ["teacher-05","teacher-06","teacher-07","teacher-08"],
                                 phone: "0954333938",
                                 email: "xxxxxx@gmail.com"),
                teachingHistory: .init(isHadTeachingExperience: false,
                                       teachingAge: 0),
                teachingStyle: .init(hopeTeachingSpendingPerHour: 1,
                                     hopeTeachingArea: [.north,.rural],
                                     hopeTeachingLocation: ["流行音樂教室"],
                                     acceptRemoteTeaching: true,
                                     acceptFreeTeaching: true,
                                     teachingType: [.oneByOne],
                                     isUnderGraduate: true,
                                     hopeLearnGender: [.male,.female],
                                     teachingReason: .profession))
    ]
    
    
}
